name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the stack
      run: docker-compose up -d
    - name: Test
      run: docker run --network container:docker-compose-php_nginx_1 appropriate/curl -s --retry 10 --retry-connrefused http://localhost/
